services:
  - type: web
    name: emry-global-tech-realm
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
